### ISSUE TITLE
How to get Structural disorder probability in keras API

### ISSUE THREAD

**Issue by ghost** [PeptoneInc/dspp-keras#25]
Hi.
I am curious to know how to get Structural disorder probability from dspp-keras API.
I have no idea where I can find it and how I can load it.

Thanks.

**Comment by ktamiola** [comment]
1. shift the propensity scores by `-2.0`, so that you are working in `-1.0; 1.0` range
2. compute the `1.0-abs(shifted_propensity_score)`

That's it! The probability of disorder is simply proportional to absolute propensity score.

Please read our preprint: http://biorxiv.org/content/early/2017/06/01/144840 We have explained how to use the disorder probability in the results section.

**Comment by ghost** [comment]
@ktamiola sorry, I have read the paper today and understood the formulation, but suddenly forgot it for a while. My silly mistake, and thanks for remembering...

**Comment by ktamiola** [comment]
Pleasure buddy! It's a relatively long thing to read! Allow me to tick this off the list and close the issue. Please reopen if more disordered questions come to your mind.

**Comment by ghost** [comment]
But what about missing values, which are zero without the -2 shift?! How does your formula handle it? By this formula, the probability of missing values is -1! Too complicated indeed!
Of course, we can filter such missing values, but process is a bit untidy.

**Comment by ktamiola** [comment]
@ErmiaAzarkhalili missing values are always a pain in the neck. One of the approaches is to back-compute and extrapolate missing values (obviously this is up to user), or use binary weights during model training in Keras.
